filebeat.autodiscover:
  providers:
    - type: docker
      labels.dedot: true
      templates:
        - condition.contains:
            docker.container.labels.logging: "true"
          config:
            - type: docker
              containers.ids:
                - "${data.docker.container.id}"
              processors:
                - add_fields:
                    target: ""
                    fields:
                      service.name: "agentic-sales-copilot"
                      env: "${APP_ENV:dev}"
                - decode_json_fields:
                    fields: ["message"]
                    target: "json"
                    overwrite_keys: true
                    add_error_key: true
                - rename:
                    fields:
                      - from: "json.@timestamp"
                        to: "@timestamp"
                    ignore_missing: true
                - copy_fields:
                    fields:
                      - from: "json.message"
                        to: "message"
                    fail_on_error: false
                    ignore_missing: true
                - add_docker_metadata: ~
                - add_host_metadata: ~
                - drop_fields:
                    fields: ["json"]
                    ignore_missing: true

queue.mem:
  events: 4096
  flush.min_events: 512
  flush.timeout: 5s

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
logging.to_files: false