# filebeat/filebeat.yml

filebeat.autodiscover:
  providers:
    - type: docker
      host: "unix:///var/run/docker.sock"
      templates:
        - condition:
            equals:
              docker.container.labels.co.elastic.logs/enabled: "true"
          config:
            - type: container
              # Tail only the discovered container's JSON log file(s)
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              stream: all
              processors:
                - add_docker_metadata: ~
                - decode_json_fields:
                    fields: ["message"]
                    target: "app"
                    overwrite_keys: true
                    add_error_key: true
              # Optional: drop empty lines early
              exclude_lines: ["^\\s*$"]

# Ship to Logstash
output.logstash:
  hosts: ["logstash:5044"]

# Increase verbosity to diagnose autodiscover decisions
logging.level: debug
logging.selectors: ["autodiscover", "docker", "input", "harvester", "cfgfile"]