services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  web:
    build: .
    # ADD a container_name
    container_name: fastapi_webhook_server
    command: poetry run gunicorn webhook_server:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers 1 --log-config logging.ini
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - TZ=Asia/Kolkata
    depends_on:
      - redis

  worker:
    build: .
    # ADD a container_name
    container_name: celery_worker
    command: poetry run celery -A app.tasks worker
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - TZ=Asia/Kolkata
    depends_on:
      - redis